Dev danil
delokoseni/StatMoney pull request #5
Opened 2024-06-21 05:14 UTC by Danil-Golotovskij

2024-06-21 05:37 UTC, lovee-python approved these changes

2024-06-21 06:42 UTC, delokoseni requested changes

2024-06-21 06:42 UTC, delokoseni commented on src/main/resources/application.properties
Мне не нравится идея хранения пароля в открытом виде, но на данном этапе с этим можно смириться. Но давайте не будет пароль все менять на свой в коде, а пока что поставим один

2024-06-21 07:20 UTC, lovee-python commented on src/main/resources/application.properties
Давайте поставим postrgres
postgres
А название бд как в моем коммите StatMoney

Поменяйте у себя в настройках пгАдмина.

2024-06-21 07:45 UTC, Danil-Golotovskij commented on src/main/resources/application.properties
Пароль в бд хранится в кэшированном виде
![gfuiwifwew](https://github.com/delokoseni/StatMoney/assets/114211026/ea4f7cf6-80fd-41ac-93f7-7b6b09368ad1)

2024-06-21 07:45 UTC, Danil-Golotovskij commented on src/main/resources/application.properties
Разве это открытый вид?

2024-06-21 07:47 UTC, lovee-python commented on src/main/resources/application.properties
Он про файл application.properties, пароль от бд

2024-06-21 07:48 UTC, Danil-Golotovskij commented on src/main/resources/application.properties
понял

2024-06-23 11:50 UTC, Nersuss approved these changes

2024-06-23 16:01 UTC, delokoseni approved these changes

2024-06-23 16:01 UTC, merged